-- Migration: auth_redesign
-- Generated by Prisma migrate diff + data migration (Task 2)

-- ── Create new tables ──
CREATE TABLE `user_identities` (
    `id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `provider_user_id` VARCHAR(191) NOT NULL,
    `metadata` JSON NULL,
    `linked_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `user_identities_user_id_idx`(`user_id`),
    UNIQUE INDEX `user_identities_provider_provider_user_id_key`(`provider`, `provider_user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `user_tokens` (
    `id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `token_hash` VARCHAR(191) NOT NULL,
    `expires_at` DATETIME(3) NULL,
    `last_used_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `revoked_at` DATETIME(3) NULL,

    UNIQUE INDEX `user_tokens_token_hash_key`(`token_hash`),
    INDEX `user_tokens_user_id_idx`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ── Add foreign keys ──
ALTER TABLE `user_identities` ADD CONSTRAINT `user_identities_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `user_tokens` ADD CONSTRAINT `user_tokens_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- ── Data migration: move feishu_union_id into user_identities ──
INSERT INTO `user_identities` (`id`, `user_id`, `provider`, `provider_user_id`, `linked_at`)
SELECT UUID(), `id`, 'feishu', `feishu_union_id`, NOW(3)
FROM `users`
WHERE `feishu_union_id` IS NOT NULL AND `feishu_union_id` <> ''
ON DUPLICATE KEY UPDATE `linked_at` = `linked_at`;

-- ── Drop legacy columns (all confirmed to exist in dev DB) ──
ALTER TABLE `users` DROP COLUMN `api_key_hash`, DROP COLUMN `avatar_url`, DROP COLUMN `encrypted_api_key`, DROP COLUMN `feishu_union_id`, DROP COLUMN `password_hash`, DROP COLUMN `sso_user_id`;
